### ISSUE TITLE
Invalid Company error message

### ISSUE THREAD

**Issue by josefausto** [OCA/commission#199] opened 2019-02-02 17:17 UTC
Hello dears
I try to use the Sales comissions module by i receive the error as the image **Invalid field: Company.**
I use Odoo11 and i have installed Sales commissions and Sales commissions by pricelist.
I try to do clicking on Save or Create Invoice, but is same answer.
Sorry maybe my configuration is bad.
Thanks
Jose
![comissions](https://user-images.githubusercontent.com/43821372/52167115-54e1e480-26e4-11e9-9420-deba87093bee.jpg)

**Comment by pedrobaeza** [comment] 2019-02-03 03:30
Please try to reproduce the problem in runbot (admin/admin): https://runbot.odoo-community.org/runbot/165/11.0

**Comment by josefausto** [comment] 2019-02-04 16:53
Thank Pedro for the fast answer
I opened Odoo in your link and i tried to reproduce the problem, but i donot find the button create, but in my Odoo i have. Look at the images.
![liquidaciones1](https://user-images.githubusercontent.com/43821372/52223334-66a5c200-2873-11e9-80f5-54b378f5dba4.jpg)
![liquidaciones2](https://user-images.githubusercontent.com/43821372/52223335-66a5c200-2873-11e9-9fa1-46ab26a44d4d.jpg)


Thanks

**Comment by pedrobaeza** [comment] 2019-02-04 16:55
Settlements are not directly created, but through the wizard...

**Comment by josefausto** [comment] 2019-02-04 16:55
Sorry i mistaken and closed, still i want keep open.

**Comment by josefausto** [comment] 2019-02-04 18:39
If you means i can do from "Settled Commisions or create Commissions Invoices" I tried in different ways and i donot have more ideas how to do.
Sorry, looks i am like a dumb trying do this, i donot get any error, but finally i donot got it work.
Thanks anyway.

**Comment by pedrobaeza** [comment] 2019-02-04 18:41
Because you are selecting incorrect date. If you want to settle a month, you have to put at least the date after the month have passed (01/02 for January for example).

**Comment by josefausto** [comment] 2019-02-04 18:51
Hi, i used the format 01/02/2019 (day/month/year) for january insettle commissions , but donot get anything.
Sorry,

**Comment by pedrobaeza** [comment] 2019-02-04 18:54
Well, don't write it, but select on the calendar for being sure. But any way, do you have invoices with commissions for settling then?

Closing this as it's clear there's no error.

**Closed as completed by pedrobaeza** 2019-02-04 18:54 UTC
