### ISSUE TITLE
Odoo 11 issue when invoicing

### ISSUE THREAD

**Issue by damsoi01** [OCA/commission#159] opened 2018-05-17 19:37 UTC
Hello,
I upgraded my platform to Odoo 11, upgraded the module as well, and it works to create settlements, only issue is with the invoicing. I get an error message. I tried adding the date, but it still does it. I'm not sure how to fix it..
Thanks!

![01](https://user-images.githubusercontent.com/17989353/40199670-73dbda2e-59d7-11e8-8209-f6e26d89092c.png)
![02](https://user-images.githubusercontent.com/17989353/40199672-73f8d066-59d7-11e8-97a4-7cd175d229c9.png)

**Comment by pedrobaeza** [comment] 2018-05-19 17:35
Please try to reproduce it on our runbot infrastructure (you have the link on the README) and specify all the detailed steps to get to the problem.

**Comment by damsoi01** [comment] 2018-05-21 05:48
Hello!
The readme file doesn't have a link other than logos and odoo community and the github page.
For what I see though, the "Make it totally multi-company aware." roadmap issue seems appropriate in my case as I do have 2 companies on my Odoo instance.
Before, when I used it on Odoo 10, it was only one company and therefore had no issue. Maybe this comes from there?
My setup is as follows:
- Multi-company (new since upgrade to Odoo 11)
- Multi-currency (same as on Odoo 10)
- Mexican accounting module (same as on Odoo 10)
- Commissions is fixed % (same as on Odoo 10)
I don't know if you need more information

**Comment by pedrobaeza** [comment] 2018-05-21 07:07
You are right about the link. Here it is:

http://3326562-11-0-f0bac8.runbot2.odoo-community.org/?db=3326562-11-0-f0bac8-all

with admin/admin or demo/demo.

Please try to reproduce the problem there.

**Comment by damsoi01** [comment] 2018-05-21 17:20
Can't seem to be able to reproduce the problem. Is there a way you could look directly into my Odoo instance?
In you demo I created a new company, different currency, assigned a product to it, and a commission product to it, and it does create the invoice nonetheless. 
I don't see a difference between your demo and my configuration...

**Comment by pedrobaeza** [comment] 2018-05-21 17:27
The usual reason for not being able to reproduce it is because you have an specific module, outdated code, etc in your deployment that provokes the problem, but it's not an Odoo problem itself, and I can't provide free support to your custom DB because I'm doing this in a voluntary base for helping in finding and tracking actual issues.

Closing this then.

**Closed as completed by pedrobaeza** 2018-05-21 17:27 UTC
